# Generated by Django 4.0 on 2022-01-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloud',
            name='box',
        ),
        migrations.RemoveField(
            model_name='cloud',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='cloud',
            name='lon',
        ),
    ]
