# Generated by Django 4.0 on 2022-01-12 16:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_cloud_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(22.9296330649 40.6254868487)', srid=4326),
        ),
    ]
